### ISSUE TITLE
Support for Keycloak 26.x.x

### ISSUE THREAD

**Issue by geffzhang** [cooperlyt/keycloak-phone-provider#131]
Keycloak 26.x.x is a major release of the open-source Identity and Access Management (IAM) solution, designed to streamline authentication and authorization for modern applications. It builds on its reputation as a robust, standards-compliant tool for securing web apps, APIs, and microservices.

Are there plans to support Keycloak version 26.x.x?

**Comment by mcboyz** [comment]
Same question, my Keycloak is version 26.1.0, can it be supported

**Comment by lucribas** [comment]
I wanted to share that I had some success getting the plugin to work with Keycloak 26.x.x.

I tested using the branch from this pull request, which has been waiting for approval for 8 months and provides support for Keycloak 25:
https://github.com/cooperlyt/keycloak-phone-provider/pull/117

Using that branch, I was able to compile the plugin and run it successfully on Keycloak 26.2.0

Here is the link to the Dockerfile I used: [[Dockerfile](https://gist.github.com/lucribas/d618c776d89bafd5e0c00c0f58c0f620)]

I hope the PR gets approved soon. In the meantime, we can use the branch from the PR directly.

**Comment by virtualathlete** [comment]
> I wanted to share that I had some success getting the plugin to work with Keycloak 26.x.x.
> 
> I tested using the branch from this pull request, which has been waiting for approval for 8 months and provides support for Keycloak 25: [#117](https://github.com/cooperlyt/keycloak-phone-provider/pull/117)
> 
> Using that branch, I was able to compile the plugin and run it successfully on Keycloak 26.2.0
> 
> Here is the link to the Dockerfile I used: [[Dockerfile](https://gist.github.com/lucribas/d618c776d89bafd5e0c00c0f58c0f620)]
> 
> I hope the PR gets approved soon. In the meantime, we can use the branch from the PR directly.

How did you set the credentials for AWS SNS?

**Comment by virtualathlete** [comment]
@lucribas i also could built it but ti can't see where to add my was credentials to actually use the service

**Comment by lucribas** [comment]
Hi @virtualathlete ,
just set the following environment variables:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION

(docker-compose.yml example)

```yml
 keycloak:
    image: keycloak:${TARGET_PREFIX}${GIT_COMMIT}
    build:
      context: ./keycloak
      dockerfile: ./Dockerfile
      target: ${DOCKER_BUILD_TARGET}
    container_name: ${TARGET_PREFIX}keycloak
    restart: ${RESTART_POLICY}
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - KC_DB=${DB_VENDOR}
      - KC_PII_ENCKEY=${KC_PII_ENCKEY}
      - KC_DB_URL_HOST=${DB_ADDR}
      - KC_DB_SCHEMA=${DB_SCHEMA}
      - KC_DB_DATABASE=${POSTGRES_DB}
      - KC_DB_USERNAME=${POSTGRES_USER}
      - KC_DB_PASSWORD=${POSTGRES_PASSWORD}
      - KC_FEATURES=persistent-user-sessions
      - KC_HEALTH_ENABLED=true
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_PASSWORD}
      - KEYCLOAK_HEALTH=${KEYCLOAK_HEALTH}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
    networks:
      - keycloak-database
      - keycloak-service
      - nginx-external
      - logging_collect
    healthcheck:
      test:
        # ["CMD", "pgrep", "-f", "java"]
        [ "CMD", "curl", "--head", "-fsSk", "${KEYCLOAK_HEALTH}", ]
      interval: 5s
      timeout: 1s
      retries: 120
    deploy:
      restart_policy:
        condition: ${RESTART_POLICY}
        delay: 2s
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201" # Logstash UDP input port
        tag: "keycloak"
```
