### ISSUE TITLE
Cant register user , sms provider not set

### ISSUE THREAD

**Issue by Kowiste** [cooperlyt/keycloak-phone-provider#37]
Im trying to use an twilio account and start keycloak with this configuration

```
version: '3'
services:


  database:
    image: mariadb:latest
#    restart: always
    ports:
      - "3306:3306"
#    volumes:
#      - "/home/data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: p0stgr@s
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: k@ycl0ck
      TZ: Asia/Shanghai

  keycloak:
    image: coopersoft/keycloak:21.0.1_phone-2.2.2
    #    restart: always
    ports:
      - 8080:8080
    command:
      - start-dev --spi-phone-message-service-default-service=dummy
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: true
      KC_PROXY: edge
      SMS_PROVIDER_SERVER: twilio
      SMS_TOKEN_EXPIRES: 180
      SMS_HOUR_MAXIMUM: 3
      TWILIO_ACCOUNT_ID: "A000000000000"
      TWILIO_AUTH_TOKEN:  "c91e000000080b5"
      TWILIO_SEND_PHONE_NUMBER: "00000000"
      DB_VENDOR: mariadb
      DB_ADDR: database
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: k@ycl0ck
      DB_PORT: 3306
    links:
      - database:database
    depends_on:
      - database
```

Create the flow and when I try to send the code I can see this in the log 
```
not specify a message sender service provider! Default provider'dummy' will be used. you can use keycloak start param '--spi-phone-default-service' specify other one.
```

Can I use the environment variable like that? Do I have to do something more?
