### ISSUE TITLE
Can't find OTP over sms for 2fa

### ISSUE THREAD

**Issue by Teut2711** [cooperlyt/keycloak-phone-provider#64]
I cloned the repository yesterday and then

cd examples
docker compose up

I edited the default service to twilio and put those(<>) attributes there.
```
  keycloak:
    image: coopersoft/keycloak:21.0.1_phone-2.2.2
    #    restart: always
    ports:
      - 8080:8080
    command:
      - start-dev --spi-phone-default-service=twilio --spi-message-sender-service-twilio-account=<> --spi-message-sender-service-twilio-token=<> --spi-message-sender-service-twilio-number=<> 
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: true
```

![image](https://github.com/cooperlyt/keycloak-phone-provider/assets/40588378/d52182af-4503-49bb-b57f-1c9c22baaec9)

I am unable to see any difference by using the "phone" theme and can't get OTP over sms option.
